name: Generate changeset

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  changesets:
    name: Changesets
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      released: ${{ steps.changesets.outputs.published }}
    steps:
      - uses: actions/checkout@v4.2.1
      - name: Setup Node.js
        uses: re-taro/actions/setup-node@v3.6.0
        with:
          node-version-file: .tool-versions
      - name: Setup GitHub App
        id: bot
        uses: re-taro/actions/gen-installation-token@v3.6.0
        with:
          app_id: ${{ secrets.APP_ID}}
          private_key: ${{ secrets.PRIVATE_KEY}}
      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1.4.8
        env:
          GITHUB_TOKEN: ${{ steps.bot.outputs.token }}
      - name: Revoke GitHub Apps token
        env:
          GITHUB_TOKEN: ${{ steps.bot.outputs.token }}
        run: |
          curl --location --silent --request DELETE \
            --url "${GITHUB_API_URL}/installation/token" \
            --header "Accept: application/vnd.github+json" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            --header "Authorization: Bearer ${GITHUB_TOKEN}"
  release:
    name: Release
    needs: changesets
    if: needs.changesets.outputs.released == 'true'
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/release.yaml
    secrets: inherit
