name: Sync Dependabot changeset
on:
  pull_request_target:
    paths:
      - "**/pnpm-lock.yaml"

jobs:
  generate-changeset:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref}}
      - name: Setup GitHub App
        id: bot
        uses: re-taro/actions/gen-installation-token@v3.7.4
        with:
          app_id: ${{ secrets.APP_ID}}
          private_key: ${{ secrets.PRIVATE_KEY}}
      - name: Generate changesets
        uses: re-taro/actions/sync-dependabot-changesets@v3.7.4
        with:
          token: ${{ steps.bot.outputs.token }}
      - name: Revoke GitHub Apps token
        env:
          GITHUB_TOKEN: ${{ steps.bot.outputs.token }}
        run: |
          curl --location --silent --request DELETE \
            --url "${GITHUB_API_URL}/installation/token" \
            --header "Accept: application/vnd.github+json" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            --header "Authorization: Bearer ${GITHUB_TOKEN}"
